# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.CharField(blank=True, max_length=256, null=True)),
                ('options', models.CharField(blank=True, max_length=256, null=True)),
                ('function', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('data_set', models.CharField(blank=True, max_length=256, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('answer_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='nodes_app.AnswerMessage')),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='nodes_app.Classifier')),
                ('parent_node', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_nodes', to='nodes_app.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
