# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('file', models.CharField(max_length=256)),
                ('options', models.CharField(max_length=256)),
                ('function', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('data_set', models.CharField(max_length=256)),
                ('answer_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='nodes_app.AnswerMessage')),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='nodes_app.Classifier')),
                ('sub_nodes', models.ManyToManyField(blank=True, null=True, to='nodes_app.Node')),
            ],
        ),
    ]
