# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermessage',
            name='file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='answermessage',
            name='function',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='answermessage',
            name='options',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='answermessage',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
