# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes_app', '0002_auto_20171207_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
