# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes_app', '0002_auto_20171206_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='data_set',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
