# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes_app', '0003_auto_20171207_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermessage',
            name='function',
        ),
        migrations.AddField(
            model_name='answermessage',
            name='function_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='function'),
        ),
    ]
