from classifiers.classifier_simple_td_idf import ClassifierSimpleTFIDF
from classifiers.classifier_base import ClassifierBase
from classifiers.classifier_equal import ClassifierEqual
from classifiers.classifier_spacy import ClassifierSpacy
